---
title: "Batch donwloading Fitbit data from several users"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
source("./R/fitbitAPI.R")
clientID <- readLines("clientID.txt") #both these tokens currently point to a temporary fitbit app
auth <- readLines("authorization.txt") #both these tokens currently point to a temporary fitbit app
```

Token Generation
=====================================  

Row {data-height=400}
-----------------------------------------------------------------------

### Step 1: Activation Link

Overall workflow: go through step 1-3 from Token Generation page for each participant. Do not proceed to step 4 on Data Download (including "testing" the tokens) until you have collected **all tokens**. Using a token deactivates it within 24 hours.

Send the link below to the Fitbit user and approve permissions. Copy the activation code from the url.

```{r}
url <- paste0("https://www.fitbit.com/oauth2/authorize?response_type=code&client_id=",
              clientID,
              "&redirect_uri=https%3A%2F%2Flocalhost%3A1410%2F&scope=activity%20heartrate%20sleep&expires_in=604800")

a("Activation link", 
  href = url, 
  target = "_blank")  
```

### Step 2: Generate access codes for user

```{r}
dat <- reactiveValues(refreshToken = "---")

textInput(inputId = "accessCode", label = "Insert the access code from the url")
actionButton(inputId = "generate1", label = "Generate token")

observeEvent(input$generate1, {
  dat$refreshToken <- activationCode(input$accessCode, clientID = clientID, auth = auth)
  shinyalert::shinyalert("Token generated")
})
```

### Step 3: Generate token

Save this token:

```{r}
h3(
  renderText(dat$refreshToken)
)
```

Warning: you can only use the generated token to gather data **once**

Data Download
=====================================  

Row {data-height=400}
-----------------------------------------------------------------------

### Step 4: Batch download data for several users

```{r}
dateRangeInput("daterange", "Date range to download (max 100 days):",
               start = Sys.Date()-14,
               end = Sys.Date())

observeEvent(input$daterange,{
  range <- (difftime(input$daterange[2], input$daterange[1], units = "days")) |> as.numeric()
  if(range>100){
    shinyalert::shinyalert("Max date range is 100 days, start date has been changed", type = "warning")
    range[1] <- (as.Date(input$daterange[2]) - 100) |> as.character()
    shiny::updateDateRangeInput(inputId = "daterange", start = input$daterange[2]-100)
  }
})

textInput(inputId = "refreshTokens", label = "Paste tokens separated by space")
actionButton(inputId = "generate2", label = "Gather data")

observeEvent(input$generate2, {
  
  updateTextInput(session, input$refreshTokens, value = "")
  showModal(modalDialog("Gathering fitbit data. Might take a couple of minutes!", footer=NULL))

  dat$refreshTokens <- strsplit(input$refreshTokens, " ") |> unlist()
  dat$accessTokens <- lapply(dat$refreshTokens, 
                             accessToken, 
                             clientID = clientID,
                             auth = auth)
  
  dat$newRefreshTokens <- sapply(dat$accessTokens, \(x){
    x$refresh_token
  })
  
  dat$out <- lapply(dat$accessTokens, \(tok){
    Sys.sleep(0.2)
    getData(token = tok$access_token,
            startDate = input$daterange[1], 
            finishDate = input$daterange[2]) |>
      integrityCheck(token = tok$refresh_token)
  })
  
  sapply(dat$out, class)
  print("------------------------")
  sapply(dat$out, colnames)
  print("------------------------")
  lapply(dat$out, \(x) print(x))
  print("------------------------")
  
  removeModal()
  
  if(dat$out[[1]] |> dim() |> is.null()){
    shinyalert::shinyalert("Something happened. Contact Leo.", type = "error")
  }else{
    if(is.null(dat$out))
      shinyalert::shinyalert("Something happened. Contact Leo.", type = "error")
  }
})
```

```{r}
downloadLink("downloadData", "Download data")
```

```{r}
output$downloadData <- downloadHandler(
    filename = "activities.xlsx",
    content = function(file) {
      writexl::write_xlsx(dat$out, file)
    }
  )
```

### New tokens

Save these tokens. The old tokens are now inactive.

```{r}
renderTable(data.frame(dat$newRefreshTokens), colnames = F, rownames = F)
```

### Sample of data

```{r}
renderTable(head(dat$out))
```
